
name:   'Surfing Bits'
url:    'http://www.surfingbits.com'
email:  'alex@eucaby.com'
author: 'Alex Dementsov'

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

safe:     true
highlighter: rouge
markdown: kramdown
timezone: 'America/Los_Angeles'
